language: go

install:
  - go get github.com/spf13/hugo

script:
  - hugo

notifications:
  webhooks:
      urls: https://api.netlify.com/build_hooks/$NETLIFY_HOOK_ID
      on_success: always
      on_failure: never
      on_start: never
      on_cancel: never
      on_error: never
  email: true
